D=[

//============ LIETVĀRDI ===========
//A
{img:"aamurs.jpg",txt:["āmurs"]},
{img:"avenes.jpg",txt:["avenes","avene"]},
{img:"atsleega.jpg",txt:["atslēga"]},
//B
{img:"baltmaize.jpg",txt:["baltmaize","maize"]},
{img:"pants.jpg",txt:["bikses"]},
{img:"bee.jpg",txt:["bite"]},
{img:"ball.png",txt:["bumba"]},
{img:"jar.jpg",txt:["burka"]},
{img:"bietes.jpg",txt:["bietes","biete"]},
{img:"bungas.jpg",txt:["bungas"]},
{img:"burkaani.jpg",txt:["burkāni","burkāns"]},


//C
{img:"chick.gif",txt:["cālis"]},
{img:"cepure.jpg",txt:["cepure"]},
{img:"cimds.jpg",txt:["cimds"]},
{img:"cirvis.jpg",txt:["cirvis"]},
{img:"citrons.jpg",txt:["citrons"]},
{img:"sugar.jpg",txt:["cukurs"]},
{img:"pig.jpg",txt:["cūka"]},
//D
{img:"delfiins.jpg",txt:["delfīns"]},
{img:"desa.jpg",txt:["desa"]},
{img:"dino.gif",txt:["dinozaurs"]},
//E
{img:"ekskavaators.jpg",txt:["ekskavātors"]},
{img:"ezis.jpg",txt:["ezis"]},
//F
{img:"fotoaparaats.jpg",txt:["fotoaprāts","fotokamera"]},
//G
{img:"table.jpg",txt:["galds"]},
{img:"gailis.jpg",txt:["gailis"]},
{img:"cow.jpg",txt:["govs"]},
{img:"graamata.gif",txt:["grāmata"]},
{img:"gurkjis.jpg",txt:["gurķis"]},
{img:"gjitaara.jpg",txt:["ģitāra"]},

//H
{img:"shark.jpg",txt:["haizivs"]},
{img:"helikopters.jpg",txt:["helikopters"]},
//I
//J
{img:"jaanjogas.jpg",txt:["jāņogas"]},
//K
{img:"cat.jpg",txt:["kaķis"]},
{img:"katls.jpg",txt:["katls"]},
{img:"goat.jpg",txt:["kaza"]},
{img:"kaaposts.jpg",txt:["kāposts"]},
{img:"kivi.jpg",txt:["kivi"]},
{img:"tree.jpg",txt:["koks"]},
{img:"krekls.png",txt:["krekls"]},
{img:"mug.png",txt:["krūze"]},
{img:"kugjis.jpg",txt:["kuģis"]},
{img:"kukuruuza.jpg",txt:["kukurūza"]},
{img:"kvadracikls.jpg",txt:["kvadracikls"]},
{img:"kjiploki.jpg",txt:["ķiploki","ķiploks"]},
{img:"kjivere.jpg",txt:["ķivere"]},
{img:"kjemme.jpg",txt:["ķemme"]},
//L
{img:"laiva.gif",txt:["laiva"]},
{img:"lion.jpg",txt:["lauva"]},
{img:"lava.jpg",txt:["lava"]},
{img:"laacis.jpg",txt:["lācis"]},
//M
{img:"house.png",txt:["māja"]},
{img:"fly.gif",txt:["muša"]},
//N
//O
{img:"egg.jpg",txt:["ola"]},
//P
{img:"mouse.jpg",txt:["pele"]},
{img:"duck.jpg",txt:["pīle"]},
{img:"flower.png",txt:["puķe"]},
//R
//S
{img:"mushroom.png",txt:["sēne"]},
{img:"dog.jpg",txt:["suns"]},
{img:"superman.gif",txt:["supermens"]},
{img:"shahs.png",txt:["šahs"]},
//T
{img:"tiger.jpg",txt:["tīģeris"]},
//U
{img:"uguns.jpg",txt:["uguns"]},
//V
{img:"whale.jpg",txt:["valis"]},
//Z
{img:"zirnji.jpg",txt:["zirņi","zirnis"]},

  
  
//============ DARBĪBAS VĀRDI  ===========
//A
//B
{img:"driving.gif",txt:["brauc"]},
//C
//D
{img:"drinking.gif",txt:["dzer"]},
//E
{img:"eating.gif",txt:["ēd"]},
//F
//G
//H
//I
{img:"walking.gif",txt:["iet"]},
//J
//K
//L
{img:"jump.gif",txt:["lec"]},
{img:"flying.gif",txt:["lido"]},
//M
{img:"fishing.gif",txt:["makšķerē"]},
//N
//O
//P
//R
//S
{img:"running.gif",txt:["skrien"]},
{img:"shooting.gif",txt:["šauj"]}
//T
//U
//V
//Z

];